# Generated by Django 2.1 on 2019-05-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40)),
                ('result', models.TextField(null=True)),
                ('dateIn', models.DateTimeField()),
                ('dateOut', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=30)),
                ('example', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Script_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=200)),
                ('script_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmd_runner.Script')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='script_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmd_runner.Script'),
        ),
        migrations.AddField(
            model_name='qparam',
            name='param_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmd_runner.Script_command'),
        ),
        migrations.AddField(
            model_name='qparam',
            name='queue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmd_runner.Queue'),
        ),
    ]
